spring:
  messages:
    basename: i18n.login
  thymeleaf:
    cache: false
  application:
    name: restful-api
  datasource:
    url: jdbc:mysql://localhost:3306/springbootwexinapp?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    platform: mysql
  jpa:
    show-sql: true
    hibernate:
      #更新或者创建数据表结构
      ddl-auto: create
  redis:
    database: 1
    host: localhost
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 100
        max-wait: 1
        max-idle: 10
        min-idle: 2
    timeout: 0
  servlet:
    multipart:
      max-file-size: 10240MB



